### ISSUE TITLE
fix for windows?

### ISSUE THREAD

**Issue by eloyfelix** [skaliev/ErrorCode#1]
Hi, since it looks you're in Windows you may be affected by this issue:

https://forum.mattermost.org/t/solved-curl-differences-linux-windows/3784/8

_It seems that Windows curl doesn’t like single quotes_

Could you please try with this?
```
curl -X POST -H 'Accept: */*' -H 'Content-Type: application/json' -d "{\"smiles\": \"CC(=O)Oc1ccccc1C(=O)O\"}" http://127.0.0.1:8080
```

let me know if it works so we'll update the blogpost.

**Comment by skaliev** [comment]
Sadly it did not work. The first time I entered the new command i had an HTTP request error.
The second time the container had some other kind of error.

```C:\Users\fabia>docker run -p 8080:8080 chembl/mcp
2020/03/27 13:37:08 Started logging stderr from function.
2020/03/27 13:37:08 Started logging stdout from function.
Forking - python [index.py]
2020/03/27 13:37:08 OperationalMode: http
2020/03/27 13:37:08 Timeouts: read: 10s, write: 10s hard: 10s.
2020/03/27 13:37:08 Listening on port: 8080
2020/03/27 13:37:08 Writing lock-file to: /tmp/.lock
2020/03/27 13:37:08 Metrics listening on port: 8081
2020/03/27 13:37:18 Upstream HTTP request error: Post http://127.0.0.1:5000/: dial tcp 127.0.0.1:5000: connect: connection refused

#2nd time i entered the command (without restarting the container)

2020/03/27 13:37:37 stderr: /home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
2020/03/27 13:37:37 stderr:   warnings.warn(message, FutureWarning)
2020/03/27 13:37:37 stderr: /home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.19.2 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
2020/03/27 13:37:37 stderr:   UserWarning)
2020/03/27 13:37:37 stderr: [2020-03-27 13:37:37,203] ERROR in app: Exception on / [POST]
2020/03/27 13:37:37 stderr: Traceback (most recent call last):
2020/03/27 13:37:37 stderr:   File "/home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
2020/03/27 13:37:37 stderr:     response = self.full_dispatch_request()
2020/03/27 13:37:37 stderr:   File "/home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
2020/03/27 13:37:37 stderr:     rv = self.handle_user_exception(e)
2020/03/27 13:37:37 stderr:   File "/home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
2020/03/27 13:37:37 stderr:     reraise(exc_type, exc_value, tb)
2020/03/27 13:37:37 stderr:   File "/home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
2020/03/27 13:37:37 stderr:     raise value
2020/03/27 13:37:37 stderr:   File "/home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
2020/03/27 13:37:37 stderr:     rv = self.dispatch_request()
2020/03/27 13:37:37 stderr:   File "/home/app/conda/envs/openfaas_tp/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
2020/03/27 13:37:37 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
2020/03/27 13:37:37 stderr:   File "index.py", line 28, in main_route
2020/03/27 13:37:37 stderr:     return handler.handle(request)
2020/03/27 13:37:37 stderr:   File "/home/app/function/handler.py", line 102, in handle
2020/03/27 13:37:37 stderr:     mol = Chem.MolFromSmiles(req.get_json()["smiles"])
2020/03/27 13:37:37 stderr: TypeError: 'NoneType' object is not subscriptable
2020/03/27 13:37:37 POST / - 500 INTERNAL SERVER ERROR - ContentLength: 290
```


#1st & 2nd time I entered the new command in the serperate shell
```
C:\Users\fabia>curl -X POST -H 'Accept: */*' -H 'Content-Type: application/json' -d "{\"smiles\": \"CC(=O)Oc1ccccc1C(=O)O\"}" http://127.0.0.1:8080
curl: (6) Could not resolve host: *
curl: (6) Could not resolve host: application

C:\Users\fabia>curl -X POST -H 'Accept: */*' -H 'Content-Type: application/json' -d "{\"smiles\": \"CC(=O)Oc1ccccc1C(=O)O\"}" http://127.0.0.1:8080
curl: (6) Could not resolve host: *
curl: (6) Could not resolve host: application
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>C:\Users\fabia>curl -X POST -H 'Accept: */*' -H 'Content-Type: application/json' -d "{\"smiles\": \"CC(=O)Oc1ccccc1C(=O)O\"}" http://127.0.0.1:8080
curl: (6) Could not resolve host: *
curl: (6) Could not resolve host: application

**Comment by eloyfelix** [comment]
ok, I realised that I only replaced the quotes related to the payload data. 
let's try replacing all of them!

```
curl -X POST -H "Accept: */*" -H "Content-Type: application/json" -d "{\"smiles\": \"CC(=O)Oc1ccccc1C(=O)O\"}" http://127.0.0.1:8080
```

**Comment by skaliev** [comment]
Now it works.
Thank you a lot! Have a nice weekend!

Best regards,
Fabian

**Comment by eloyfelix** [comment]
No problem :)
Have a nice weekend you too!
